name: Github Actions
on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]
jobs: 
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps: 
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install outer modules
        run: npm i
      - name: install client modules
        run: npm i --prefix client
      - name: build project
        run: npm run build
      - name: tests
        run: npm run test
